## NUMPY

NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed.

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

a powerful N-dimensional array object
sophisticated (broadcasting) functions
tools for integrating C/C++ and Fortran code
useful linear algebra, Fourier transform, and random number capabilities
Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Library documentation: http://www.numpy.org/

https://cloudxlab.com/blog/numpy-pandas-introduction/

In [1]:
from numpy import *


In [9]:
# declare a vector using a list as the argument
v = array([1,2,3,4])
v

array([1, 2, 3, 4])

In [10]:
v[0]

1

In [11]:
v*2,v.ndim,v.size,v.shape,v.nbytes,v.itemsize

(array([2, 4, 6, 8]), 1, 4, (4,), 16, 4)

In [12]:
# declare a matrix using a nested list as the argument
M = array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [16]:
M[0]+M[1]

array([4, 6])

In [13]:
M.shape

(2, 2)

In [26]:
# still the same core type with different shapes
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

In [27]:
M.ndim

2

In [28]:
M.size

4

In [29]:
M.nbytes


32

In [30]:
M.itemsize

8

In [14]:
import numpy as np

In [15]:
l=[1,2,3]
np.array(l)*2

array([2, 4, 6])

In [41]:
a=array([9,8,7,6])
b=array([1,2,3,4])
a-b

array([8, 6, 4, 2])

In [43]:
array([1,2,3])*2

array([2, 4, 6])

In [45]:
# assign new value
M[0,0] = 7
M

array([[7, 2],
       [3, 4]])

In [46]:
M[0][0]

7

In [34]:
linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [7]:
logspace(0, 10, 10, base=e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [9]:
x,y= mgrid[0:6, 0:7]
x

array([[0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5]])

In [4]:
y

array([[0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6]])

In [49]:
y[2,3]

3

In [18]:
random.randint(5,size=5)

array([2, 1, 2, 1, 0])

In [41]:
random.rand(5,5)

array([[0.57691425, 0.2772851 , 0.75431089, 0.36285946, 0.03305261],
       [0.76052272, 0.44213975, 0.72582107, 0.88923279, 0.24689168],
       [0.93270648, 0.60823931, 0.17832054, 0.22792542, 0.35722511],
       [0.87697827, 0.8168642 , 0.16774599, 0.67654633, 0.49769013],
       [0.80635796, 0.03942636, 0.08795795, 0.04808045, 0.31005786]])

In [42]:
# normal distribution
random.randn(5,5)

array([[ 2.58794108,  0.88828311,  1.22744631,  0.46248543, -0.22815777],
       [-1.18668026, -0.55018146,  0.98193193,  0.99658   ,  0.14023881],
       [ 0.16934126, -0.48895115,  0.24294243,  1.39917634, -1.12598912],
       [ 1.89329405, -1.58881764, -0.10968497, -0.13841152, -0.39619418],
       [ 2.30253843, -0.21184128,  0.31663321, -0.92822557, -0.18878814]])

In [22]:
diag([1,2,3])
diag([1,1,1,1])

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [25]:
# slicing works just like with lists
A = array([1,2,3,4,5])
A[1:3]

array([2, 3])

In [46]:
A = array([[n+m*10 for n in range(5)] for m in range(6)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44],
       [50, 51, 52, 53, 54]])

In [23]:
# index masking
B = array([n for n in range(5)])
print(B)
row_mask = array([True, False, True, False, False])
B[row_mask]

[0 1 2 3 4]


array([0, 2])

In [25]:
import numpy as np

In [26]:
x=np.arange(20)
y=np.where(x%2==0,'even','odd')
y

array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd'], dtype='<U4')

In [53]:
x.reshape(5,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [54]:
import numpy as np

2.Replace all odd numbers in arr with -1 without changing arr

In [55]:
arr = np.arange(10)
print(arr)
out = np.where(arr % 2 == 1, -1, arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [56]:
out = np.where(arr % 2 == 1, -1, 0)
out

array([ 0, -1,  0, -1,  0, -1,  0, -1,  0, -1])

3.Convert a 1D array to a 2D array with 2 rows

In [28]:
arr = np.arange(10)
arr.reshape(-1, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

4.Stack arrays a and b vertically

In [1]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
#print(a,b)
# Answers
# Method 1:
print(np.concatenate([a, b], axis=0))

# Method 2:
print(np.vstack([a, b]))

# Method 3:
print(np.r_[a, b])

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [7]:
np.split(np.vstack([a, b]),4)


[array([[0, 1, 2, 3, 4]]),
 array([[5, 6, 7, 8, 9]]),
 array([[1, 1, 1, 1, 1]]),
 array([[1, 1, 1, 1, 1]])]

5.Stack the arrays a and b horizontally.

In [59]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Answers
# Method 1:
np.concatenate([a, b], axis=1)

# Method 2:
#np.hstack([a, b])

# Method 3:
#np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

6.Get the positions where elements of a and b match

In [89]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#print(np.where(a == b))
#returns the index of matching elements

Basic Functions

In [92]:
a1=a.reshape(2,-1)
b1=b.reshape(5,-1)
print(a1,b1)
np.matmul(a1,b1)

[[1 2 3 2 3]
 [4 3 4 5 6]] [[ 7  2]
 [10  2]
 [ 7  4]
 [ 9  4]
 [ 9  8]]


array([[ 93,  50],
       [185,  98]])

In [68]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.44461715 0.33369784]
 [0.13262267 0.32007657]]


Array Indexing

In [ ]:
np.sum()

In [78]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1,2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [79]:
a[np.arange(3),np.array([0,1,0])]+=5
a

array([[ 6,  2],
       [ 3,  9],
       [10,  6]])

In [80]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Array Math

In [19]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Broadcast

In [83]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [87]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
#x[np.arange(4),v]
x[[0,1,3],v]

array([ 2,  4, 11])

In [21]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


## Write a Python program to create a random vector of size 10 and sort it.

In [22]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.97651097 0.15385102 0.39153707 0.2564644  0.45479494 0.52172714
 0.25746289 0.43902154 0.14108535 0.13972024]
Sorted array:
[0.13972024 0.14108535 0.15385102 0.2564644  0.25746289 0.39153707
 0.43902154 0.45479494 0.52172714 0.97651097]


## Write a Python program to get the n largest values of an array.

In [25]:

import numpy as np
#x = np.arange(10)
x=np.random.random(10)
print("Original array:")
print(x)
#np.random.shuffle(x)
n = 3
print (x[np.argsort(x)[-n:]])

Original array:
[0.07565849 0.87162414 0.07507523 0.81884086 0.93301425 0.56206005
 0.07135508 0.6786472  0.67928862 0.11214531]
[0.81884086 0.87162414 0.93301425]


In [33]:
n=np.matrix([[1,2,3],[6,7,8]])
n

matrix([[1, 2, 3],
        [6, 7, 8]])

 1.Determinant Of A Matrix (100 Marks)
Determinant is a very useful value in linear algebra. It calculated from the diagonal elements of a square matrix.
The NumPy module also comes with a number of built-in routines for linear algebra calculations. 
The numpy.linalg.det() function calculates the determinant of the input matrix.
Now, Given a square matrix calculate and output the determinant of the matrix.

Input Format
First line will contain an Integer N, denoting the size of square matrix.
Each of the next N lines contains N Integers denoting the elements of the matrix.

Constraints
2 <= N <= 20

Output Format
Output a number upto 1 decimal place denoting the determinant of the Matrix.

Sample TestCase 1
Input
2
4 3 
2 1
Output
-2.0
Explanation
Determinant = (4 * 1 ) - (3 * 2 ) = -2